/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.ImageIcon;


/**
 *
 * @author MSI
 */
public class LIsName extends javax.swing.JFrame {

    /**
     * Creates new form LIsName
     */
    public LIsName() {
        initComponents();
    }
    public  void ClearDate(){
        box1.setSelected(false);
        box2.setSelected(false);
        box3.setSelected(false);
        box4.setSelected(false);
        box5.setSelected(false);
        box6.setSelected(false);
//        box7.setSelected(false);
        txtname.setText("");
        lbphoto.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        box1 = new javax.swing.JCheckBox();
        box2 = new javax.swing.JCheckBox();
        box3 = new javax.swing.JCheckBox();
        box4 = new javax.swing.JCheckBox();
        box5 = new javax.swing.JCheckBox();
        box6 = new javax.swing.JCheckBox();
        txtname = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btlExit = new javax.swing.JButton();
        btlclear1 = new javax.swing.JButton();
        lbphoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("!!Kh Ang MuraFastHand", 1, 36)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("រូបថត");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 350, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 109, 165));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("សកលវិទ្យាល័យជាតិគ្របគ្រង់");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, 79));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ឈ្មោះសមាជិតក្រុម");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 350, 60));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ឈ្មោះ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 350, 60));

        box1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(box1);
        box1.setFont(new java.awt.Font("Khmer OS System", 0, 24)); // NOI18N
        box1.setForeground(new java.awt.Color(255, 255, 255));
        box1.setText("1. Chea Sophon");
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        getContentPane().add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 240, 50));

        box2.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(box2);
        box2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        box2.setForeground(new java.awt.Color(255, 255, 255));
        box2.setText("2. Um Rachny ");
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });
        getContentPane().add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 240, 50));

        box3.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(box3);
        box3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        box3.setForeground(new java.awt.Color(255, 255, 255));
        box3.setText("3. CHAN DAKHAIR");
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });
        getContentPane().add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, 50));

        box4.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(box4);
        box4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        box4.setForeground(new java.awt.Color(255, 255, 255));
        box4.setText("4. ស្រុន​ សុវណ្ណារ័ត");
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });
        getContentPane().add(box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 240, 50));

        box5.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(box5);
        box5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        box5.setForeground(new java.awt.Color(255, 255, 255));
        box5.setText("5.PONH SOKMEAN");
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });
        getContentPane().add(box5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 240, 50));

        box6.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(box6);
        box6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        box6.setForeground(new java.awt.Color(255, 255, 255));
        box6.setText("6.ROEUNG SREYNA");
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });
        getContentPane().add(box6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, 50));

        txtname.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 0, 204)));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 360, 70));

        jPanel1.setBackground(new java.awt.Color(63, 66, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btlExit.setBackground(new java.awt.Color(153, 0, 102));
        btlExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btlExit.setForeground(new java.awt.Color(0, 0, 0));
        btlExit.setText("ចាកចេញ");
        btlExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlExitActionPerformed(evt);
            }
        });
        jPanel1.add(btlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 183, 61));

        btlclear1.setBackground(new java.awt.Color(153, 0, 102));
        btlclear1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btlclear1.setForeground(new java.awt.Color(0, 0, 0));
        btlclear1.setText("សម្អាត");
        btlclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlclear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btlclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 503, 183, 61));

        lbphoto.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 7, 7, new java.awt.Color(153, 0, 0)));
        jPanel1.add(lbphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 240, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 630));

        setSize(new java.awt.Dimension(1318, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
        String Photo = "D:\\JAVA\\Final\\src\\Login\\Photo\\ny.jpg";
        String Name = "Um Rachny";
        if(box2.isSelected()){
            txtname.setText(Name);
            lbphoto.setIcon(new  ImageIcon(Photo));
        }
        else{
            txtname.setText(Name);
            lbphoto.setIcon(null);
        }
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
        String Name = "CHAN DAKHAIR";
        String Photo = "D:\\JAVA\\Final\\src\\Login\\Photo\\khear.jpg";
        if(box3.isSelected()){
            txtname.setText(Name);
            lbphoto.setIcon(new  ImageIcon(Photo));
        }
        else{
            txtname.setText(Name);
            lbphoto.setIcon(null);
        }
            
    }//GEN-LAST:event_box3ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
        String Photo = "D:\\JAVA\\Final\\src\\Login\\Photo\\sokmean.jpg";
        String Name = "PONH SOKMEAN";
        if(box5.isSelected()){
            txtname.setText(Name);
            lbphoto.setIcon(new ImageIcon(Photo));
        }
        else{
            txtname.setText("");
            lbphoto.setIcon(null);
            
        }
    }//GEN-LAST:event_box5ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        String Photo="D:\\JAVA\\Final\\src\\Login\\Photo\\phon.jpg";
        String Name ="CHEA SOPHON";
        if(box1.isSelected()){
            txtname.setText(Name);
            lbphoto.setIcon(new  ImageIcon(Photo));
        }
        else{
            txtname.setText("");
            lbphoto.setIcon(null);
        }
    }//GEN-LAST:event_box1ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
        String Photo = "D:\\JAVA\\Final\\src\\Login\\Photo\\na.jpg";
        String Name = "ROEUNG SREYNA";
        if(box6.isSelected()){
            txtname.setText(Name);
            lbphoto.setIcon(new  ImageIcon(Photo));
        }
        else{
            txtname.setText("");
            lbphoto.setIcon(null);
        }
    }//GEN-LAST:event_box6ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
        String Photo = "";
        String Name = "ស្រុន​ សុវណ្ណារ័ត";
        if(box4.isSelected()){
            txtname.setText(Name);
            lbphoto.setIcon(new  ImageIcon(Photo));
        }
        else{
            txtname.setText("");
            lbphoto.setIcon(null);
        }
    }//GEN-LAST:event_box4ActionPerformed

    private void btlExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlExitActionPerformed
        // TODO add your handling code here:
        login.main(null);
        this.dispose();
    }//GEN-LAST:event_btlExitActionPerformed

    private void btlclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlclear1ActionPerformed
        // TODO add your handling code here:
        ClearDate();
    }//GEN-LAST:event_btlclear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIsName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIsName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIsName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIsName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIsName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box1;
    private javax.swing.JCheckBox box2;
    private javax.swing.JCheckBox box3;
    private javax.swing.JCheckBox box4;
    private javax.swing.JCheckBox box5;
    private javax.swing.JCheckBox box6;
    private javax.swing.JButton btlExit;
    private javax.swing.JButton btlclear1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
