/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Driver;
//import com.mysql.jdbc.PreparedStatement;
//import java.awt.Window;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MSI
 */
public class MainForm extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;
    String sql;

    Connection connectin() {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
//            Servername. username"root",password" ";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "");
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println("Connection Error.....!" + e);
        }
        return con;
    }

    public void Getdata() {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        sql = "SELECT * FROM `num`";
        try {
            ps = (PreparedStatement) connectin().prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                Object row[] = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10),
                    rs.getString(11),
                    rs.getString(12),
                    rs.getString(13),
                    rs.getString(14),
                    rs.getString(15),
                    rs.getString(16),};
                model.addRow(row);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ClearData() {
        txtid.setText("");
        txtname.setText("");
        buttonGroup1.clearSelection();
        txtdate.setDate(null);
        buttonGroup2.clearSelection();
        txtbuiding.setSelectedIndex(0);
        txtsemester.setSelectedIndex(0);
        txtdemp.setSelectedIndex(0);
        txtphon.setText("");
        txtprice.setText("");
        btnphoto.setText("");
        lbphoto.setIcon(null);
        txttime.setSelectedIndex(0);
        txtstat.setDate(null);
        txtfinish.setDate(null);
        txtclass.setSelectedIndex(0);

    }

    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jFrame6 = new javax.swing.JFrame();
        jFrame7 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbphoto = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtfinish = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txttime = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dayone = new javax.swing.JCheckBox();
        daytwo = new javax.swing.JCheckBox();
        txtstat = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtgender = new javax.swing.JLabel();
        male = new javax.swing.JCheckBox();
        famale = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txtphon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtyear = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtsemester = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtdemp = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtclass = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtbuiding = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsort = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnphoto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame6Layout.setVerticalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame7Layout = new javax.swing.GroupLayout(jFrame7.getContentPane());
        jFrame7.getContentPane().setLayout(jFrame7Layout);
        jFrame7Layout.setHorizontalGroup(
            jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame7Layout.setVerticalGroup(
            jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1452, 1450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(211, 175, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(1500, 830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff Student In University");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 510, 60));

        lbphoto.setBackground(new java.awt.Color(11, 37, 66));
        lbphoto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbphoto.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 160, 200));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/images.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 200, 200));

        jPanel2.setBackground(new java.awt.Color(153, 105, 175));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Finish");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 87, 30));
        jPanel2.add(txtfinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 240, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Strat");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 170, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Price");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, 170, 30));

        txtprice.setBackground(new java.awt.Color(204, 204, 204));
        txtprice.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtprice.setForeground(new java.awt.Color(255, 0, 0));
        txtprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 210, 240, 30));

        txttime.setBackground(new java.awt.Color(255, 255, 255));
        txttime.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txttime.setForeground(new java.awt.Color(0, 102, 102));
        txttime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moning", "Afternoom", "Nigth" }));
        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        jPanel2.add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, 240, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Time");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 170, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 170, 70));

        dayone.setBackground(new java.awt.Color(255, 20, 101));
        buttonGroup2.add(dayone);
        dayone.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dayone.setForeground(new java.awt.Color(255, 255, 255));
        dayone.setText("Saturday - Sunday");
        jPanel2.add(dayone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 240, 30));

        daytwo.setBackground(new java.awt.Color(129, 22, 22));
        buttonGroup2.add(daytwo);
        daytwo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        daytwo.setForeground(new java.awt.Color(255, 255, 255));
        daytwo.setText("Monday - Friday");
        jPanel2.add(daytwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 240, 30));

        txtstat.setBackground(new java.awt.Color(255, 255, 255));
        txtstat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, 240, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        txtid.setBackground(new java.awt.Color(204, 204, 204));
        txtid.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 0, 0));
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 40));

        txtname.setBackground(new java.awt.Color(204, 204, 204));
        txtname.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 0, 0));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 200, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 30));

        txtgender.setBackground(new java.awt.Color(255, 255, 255));
        txtgender.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtgender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtgender.setText("Gender");
        jPanel2.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 30));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 80, 30));

        famale.setBackground(new java.awt.Color(255, 51, 204));
        buttonGroup1.add(famale);
        famale.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        famale.setForeground(new java.awt.Color(255, 255, 255));
        famale.setText("FaMale");
        famale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famaleActionPerformed(evt);
            }
        });
        jPanel2.add(famale, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 110, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Date Of Birth");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, -1));

        txtdate.setBackground(new java.awt.Color(255, 255, 255));
        txtdate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Phone");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, -1));

        txtphon.setBackground(new java.awt.Color(204, 204, 204));
        txtphon.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtphon.setForeground(new java.awt.Color(255, 0, 0));
        txtphon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonActionPerformed(evt);
            }
        });
        jPanel2.add(txtphon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Year");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 170, -1));

        txtyear.setBackground(new java.awt.Color(255, 255, 255));
        txtyear.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtyear.setForeground(new java.awt.Color(0, 102, 102));
        txtyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year1", "Year2", "Year3", "Year4" }));
        txtyear.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtyearComponentShown(evt);
            }
        });
        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });
        jPanel2.add(txtyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 220, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Semester");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 170, 30));

        txtsemester.setBackground(new java.awt.Color(255, 255, 255));
        txtsemester.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtsemester.setForeground(new java.awt.Color(0, 102, 102));
        txtsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester1", "Semester2", "Semester3" }));
        txtsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsemesterActionPerformed(evt);
            }
        });
        jPanel2.add(txtsemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 220, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DepartMent");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 170, 40));

        txtdemp.setBackground(new java.awt.Color(255, 255, 255));
        txtdemp.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtdemp.setForeground(new java.awt.Color(0, 102, 102));
        txtdemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information Technology", "ManageMent", "RotBot", "Accountting" }));
        jPanel2.add(txtdemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 280, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Class");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 170, 30));

        txtclass.setBackground(new java.awt.Color(255, 255, 255));
        txtclass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtclass.setForeground(new java.awt.Color(0, 102, 102));
        txtclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20E", "10A", "10B", "15C" }));
        jPanel2.add(txtclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 220, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buiding");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 170, 30));

        txtbuiding.setBackground(new java.awt.Color(255, 255, 255));
        txtbuiding.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtbuiding.setForeground(new java.awt.Color(0, 102, 102));
        txtbuiding.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buiding A", "Buiding B", "Buiding C", "Buiding D", "Buiding E" }));
        jPanel2.add(txtbuiding, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 220, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 1500, 250));

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("National University Of ManageMent");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1450, 90));

        btnclear.setBackground(new java.awt.Color(255, 102, 255));
        btnclear.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 0, 51));
        btnclear.setText("Clear");
        btnclear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 2, 4), 1, true));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 720, 120, 40));

        btnsave.setBackground(new java.awt.Color(0, 0, 204));
        btnsave.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 0, 51));
        btnsave.setText("Save");
        btnsave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 2, 4), 1, true));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 120, 40));

        btnupdate.setBackground(new java.awt.Color(226, 229, 185));
        btnupdate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 255, 0));
        btnupdate.setText("Update");
        btnupdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 2, 4), 1, true));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, 120, 40));

        btndelete.setBackground(new java.awt.Color(19, 168, 16));
        btndelete.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btndelete.setForeground(new java.awt.Color(204, 0, 51));
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 2, 4), 1, true));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 720, 120, 40));

        btnsort.setBackground(new java.awt.Color(255, 204, 153));
        btnsort.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnsort.setForeground(new java.awt.Color(255, 0, 51));
        btnsort.setText("Sort");
        btnsort.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 2, 4), 1, true));
        btnsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsortActionPerformed(evt);
            }
        });
        jPanel1.add(btnsort, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, 120, 40));

        btnexit.setBackground(new java.awt.Color(153, 153, 255));
        btnexit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 0, 51));
        btnexit.setText("Exit");
        btnexit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 2, 4), 1, true));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 720, 120, 40));

        btnphoto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnphoto.setForeground(new java.awt.Color(255, 102, 0));
        btnphoto.setText("Photo");
        btnphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 210, 160, 40));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "dob", "Phone", "Year", "Semester", "Demp", "Class", "Buiding", "Date", "Start", "Finish", "Time", "Price", "Photo"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1460, 190));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 150, 30));

        txtsearch.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtsearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 209, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, 1450, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    private void txtsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsemesterActionPerformed

    private void txtyearComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtyearComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearComponentShown

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do You Want To Clear Deta ?", "Information Students", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            ClearData();
            JOptionPane.showMessageDialog(null, "Deta clear Is SuccessFully....!");
        } else {
            JOptionPane.showMessageDialog(null, "Deta clear Is Not SuccessFully....!");
        }
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do You Want To Save Data ?", "Information StuDent", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            int id = Integer.parseInt(txtid.getText());
            String name = txtname.getText();
            String gender = (male.isSelected() == true) ? "Male" : "Famale";
            SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
            String birth = date.format(txtdate.getDate());
            String phone = txtphon.getText();
            String year = txtyear.getSelectedItem().toString();
            String Semester = txtsemester.getSelectedItem().toString();
            String demp = txtdemp.getSelectedItem().toString();
            String Class = txtclass.getSelectedItem().toString();
            String Buiding = txtbuiding.getSelectedItem().toString();
            String Date;
            if (dayone.isSelected() == true) {
                Date = "Moday - Friday";
            } else {
                Date = "Saturday - Sunday";
            }
            String start = date.format(txtstat.getDate());
            String finish = date.format(txtfinish.getDate());
            String Time = txttime.getSelectedItem().toString();
            String price = txtprice.getText();
            String photo = btnphoto.getText();
            sql = "INSERT INTO `num`(`id`, `name`, `gender`, `birth`, `phone`, `years`, `semester`, `department`, `class`, `building`, `date`, `start`, `finish`, `time`, `price`, `photos`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            try {
                ps = (PreparedStatement) connectin().prepareStatement(sql);
                ps.setInt(1, id);
                ps.setString(2, name);
                ps.setString(3, gender);
                ps.setString(4, birth);
                ps.setString(5, phone);
                ps.setString(6, year);
                ps.setString(7, Semester);
                ps.setString(8, demp);
                ps.setString(9, Class);
                ps.setString(10, Buiding);
                ps.setString(11, Date);
                ps.setString(12, start);
                ps.setString(13, finish);
                ps.setString(14, Time);
                ps.setString(15, price + "$" );
                ps.setString(16, photo);
                int i = ps.executeUpdate();
                if (i > 0) {
                    DefaultTableModel model = (DefaultTableModel) Table.getModel();
                    model.setRowCount(0);
                    Getdata();

                }
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Date Save SuccessFully...!");
        } else {
            JOptionPane.showMessageDialog(null, "Date Save Not SuccessFully...!");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do You Want To Update Data ?", "Information Student", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            try {
                ps = (PreparedStatement) connectin().prepareStatement("UPDATE `num` SET `id`=?,`name`=?,`gender`=?,`birth`=?,`phone`=?,`years`=?,`semester`=?,`department`=?,`class`=?,`building`=?,`date`=?,`start`=?,`finish`=?,`time`=?,`price`=?,`photos`=? WHERE id=?");
                ps.setInt(1, Integer.parseInt(txtid.getText()));
                ps.setString(2, txtname.getText());
                ps.setString(3, male.isSelected() == true ? "Male" : "Famale");
                SimpleDateFormat df = new SimpleDateFormat("yyy-MM-dd");
                ps.setString(4, df.format(txtdate.getDate()));
                ps.setString(5, txtphon.getText());
                ps.setString(6, txtyear.getSelectedItem().toString());
                ps.setString(7, txtsemester.getSelectedItem().toString());
                ps.setString(8, txtdemp.getSelectedItem().toString());
                ps.setString(9, txtclass.getSelectedItem().toString());
                ps.setString(10, txtbuiding.getSelectedItem().toString());
                String Date;
                if (dayone.isSelected() == true) {
                    Date = "Monday - Friday";
                } else {
                    Date = "Saturday - Sunday";
                }
                ps.setString(11, Date);
                ps.setString(12, df.format(txtstat.getDate()));
                ps.setString(13, df.format(txtfinish.getDate()));
                ps.setString(14, txttime.getSelectedItem().toString());
                ps.setString(15, txtprice.getText());
                ps.setString(16, btnphoto.getText());
                ps.setInt(17, Integer.parseInt(txtid.getText()));
                int index = ps.executeUpdate();
                if (index > 0) {
                    DefaultTableModel model = (DefaultTableModel) Table.getModel();
                    model.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "You Can Update Data Successfulyy....!");
                    Getdata();
                    
                }
                ClearData();
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data Update Not Compled...!");

        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do You Want To Delete Data?", "Information Student", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            try {
                ps = (PreparedStatement) connectin().prepareStatement("DELETE FROM `num` WHERE id= ?");
                ps.setInt(1, Integer.parseInt(txtid.getText()));
                int index = ps.executeUpdate();
                if (index > 0) {
                    DefaultTableModel model = (DefaultTableModel) Table.getModel();
                    model.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "You Can Delete Data SuccessFully...!");
                    Getdata();
                    ClearData();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsortActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do You Want To Exit ?", "Information Student", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);

        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotoActionPerformed
        // TODO add your handling code here:
        JFileChooser choos = new JFileChooser();
        choos.showOpenDialog(null);
        File file = choos.getSelectedFile();
        String filename = file.getAbsolutePath();
        btnphoto.setText(filename);
        ImageIcon icon = new ImageIcon(filename);
        lbphoto.setIcon(icon);

    }//GEN-LAST:event_btnphotoActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        int row = Table.getSelectedRow();
        txtid.setText(model.getValueAt(row, 0).toString());
        txtname.setText(Table.getValueAt(row, 1).toString());
        String Gender = model.getValueAt(row, 2).toString();
        if (Gender.equalsIgnoreCase("Male")) {
            male.setSelected(true);
        } else {
            famale.setSelected(true);
        }
        SimpleDateFormat df = new SimpleDateFormat("yyy-MM-dd");
        try {
            java.util.Date st = df.parse(Table.getValueAt(row, 3).toString());
            txtdate.setDate(st);
        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);

        }
        txtphon.setText(Table.getValueAt(row, 4).toString());
        txtyear.setSelectedItem(Table.getValueAt(row, 5).toString());
        txtsemester.setSelectedItem(Table.getValueAt(row, 6).toString());
        txtdemp.setSelectedItem(Table.getValueAt(row, 7).toString());
        txtclass.setSelectedItem(Table.getValueAt(row, 8).toString());
        txtbuiding.setSelectedItem(Table.getValueAt(row, 9).toString());
        String date = model.getValueAt(row, 10).toString();
        if (date.equalsIgnoreCase("Monday - friday")) {
            dayone.setSelected(true);
        } else {
            daytwo.setSelected(true);
        }
        try {
            java.util.Date st = df.parse(Table.getValueAt(row, 11).toString());
            txtstat.setDate(st);
        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            java.util.Date st = df.parse(Table.getValueAt(row, 12).toString());
            txtfinish.setDate(st);
        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txttime.setSelectedItem(Table.getValueAt(row, 13).toString());
        txtprice.setText(Table.getValueAt(row, 14).toString());
        lbphoto.setIcon(new javax.swing.ImageIcon(model.getValueAt(row, 15).toString()));

    }//GEN-LAST:event_TableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Getdata();
    }//GEN-LAST:event_formWindowOpened

    private void famaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_famaleActionPerformed

    private void txtphonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        try {
            sql = "SELECT * FROM `num` where id=?";
            ps = (PreparedStatement) connectin().prepareStatement(sql);
            ps.setString(1, txtsearch.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                String Setid = rs.getString("id");
                txtid.setText(Setid);
                String setname = rs.getString("name");
                txtname.setText(setname);
                String setgender = rs.getNString("gender");
                if (setgender.equalsIgnoreCase("Male")) {
                    male.setSelected(true);
                } else {
                    famale.setSelected(true);
                }
                txtdate.setDate(rs.getDate("birth"));
                String setphone = rs.getString("phone");
                txtphon.setText(setphone);
                String setyear = rs.getString("years");
                switch (setyear) {
                    case "Yaer 1" ->
                        txtyear.setSelectedItem(0);
                    case "Year 2" ->
                        txtyear.setSelectedItem(1);
                    case "Year 3" ->
                        txtyear.setSelectedItem(2);
                    default ->
                        txtyear.setSelectedItem(3);

                }
                String Semester = rs.getString("semester");
                switch (Semester) {
                    case "Semester 1" ->
                        txtsemester.setSelectedItem(0);
                    case "Semester 2" ->
                        txtsemester.setSelectedItem(1);
                    default ->
                        txtsemester.setSelectedItem(2);
                }
                String Demp = rs.getString("department");
                switch (Demp) {
                    case "Information Technology" ->
                        txtdemp.setSelectedItem(0);
                    case "ManageMent" ->
                        txtdemp.setSelectedItem(1);
                    case "RotBot" ->
                        txtdemp.setSelectedItem(2);
//                Information Technology, ManageMent, RotBot, Accountting       
                    default ->
                        txtdemp.setSelectedItem(3);
                }
                String Class = rs.getString("class");
                switch (Class) {
                    case "20E" ->
                        txtclass.setSelectedItem(0);
                    case "10A" ->
                        txtclass.setSelectedItem(1);
                    case "10B" ->
                        txtclass.setSelectedItem(2);
//                     20E, 10A, 10B, 15C   

                    default ->
                        txtclass.setSelectedItem(0);
                }
                String buiding = rs.getString("building");
//                Buiding A, Buiding B, Buiding C, Buiding D, Buiding E
                switch (buiding) {
                    case " Buiding A" ->
                        txtbuiding.setSelectedItem(0);
                    case " Buiding B" ->
                        txtbuiding.setSelectedItem(1);
                    case " Buiding C" ->
                        txtbuiding.setSelectedItem(2);
                    case " Buiding D" ->
                        txtbuiding.setSelectedItem(3);

                    default ->
                        txtbuiding.setSelectedItem(4);

                }
                String setDate = rs.getString("date");
                if (setDate.equalsIgnoreCase("Monday - Friday")) {
                    dayone.setSelected(true);
                } else {
                    daytwo.setSelected(true);
                }
                txtstat.setDate(rs.getDate("start"));
                txtfinish.setDate(rs.getDate("finish"));
                String settime = rs.getString("time");
                switch (settime) {
                    case "Morning" ->txttime.setSelectedIndex(0);
                    case "Afternoon" ->txttime.setSelectedIndex(1);
                    default ->txttime.setSelectedIndex(2);
                }
                String setprice = rs.getString("price");
                txtprice.setText(setprice);
                String setphotos = rs.getString("photos");
                btnphoto.setText(setphotos);
                ImageIcon icon = new ImageIcon(setphotos);
                lbphoto.setIcon(icon);
            
            }
            else{
                ClearData();
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
//        ClearData();
//        if (JOptionPane.showConfirmDialog(null, "Do You Want To Search data ?", "Information Student", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
//            DefaultTableModel model = (DefaultTableModel) Table.getModel();
//            
//        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnphoto;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsort;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox dayone;
    private javax.swing.JCheckBox daytwo;
    private javax.swing.JCheckBox famale;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JFrame jFrame7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JCheckBox male;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JComboBox<String> txtbuiding;
    private javax.swing.JComboBox<String> txtclass;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txtdemp;
    private com.toedter.calendar.JDateChooser txtfinish;
    private javax.swing.JLabel txtgender;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphon;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JComboBox<String> txtsemester;
    private com.toedter.calendar.JDateChooser txtstat;
    private javax.swing.JComboBox<String> txttime;
    private javax.swing.JComboBox<String> txtyear;
    // End of variables declaration//GEN-END:variables
}
