/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author MSI
 */
public class Rigister extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Rigister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcomfimpass = new javax.swing.JPasswordField();
        txtpass = new javax.swing.JPasswordField();
        btnconcle = new javax.swing.JButton();
        btnresgister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 160, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resgister  Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -7, 383, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Comfim password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 220, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("UserName");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 210, 50));

        txtusername.setBackground(new java.awt.Color(255, 255, 255));
        txtusername.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(51, 51, 51));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 280, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 210, 50));

        txtcomfimpass.setBackground(new java.awt.Color(255, 255, 255));
        txtcomfimpass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtcomfimpass.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtcomfimpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 280, 40));

        txtpass.setBackground(new java.awt.Color(255, 255, 255));
        txtpass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 280, 40));

        btnconcle.setBackground(new java.awt.Color(255, 0, 51));
        btnconcle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnconcle.setForeground(new java.awt.Color(255, 255, 255));
        btnconcle.setText("Cancle");
        btnconcle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconcleActionPerformed(evt);
            }
        });
        getContentPane().add(btnconcle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 110, 30));

        btnresgister.setBackground(new java.awt.Color(0, 0, 255));
        btnresgister.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnresgister.setForeground(new java.awt.Color(255, 255, 255));
        btnresgister.setText("Register");
        btnresgister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresgisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnresgister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 110, 30));

        setSize(new java.awt.Dimension(846, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private  void ClearData(){
        txtusername.setText("");
        txtpass.setText(null);
        txtcomfimpass.setText(null);
        
    }
    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnconcleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconcleActionPerformed
        // TODO add your handling code here:
//        if(JOptionPane.showConfirmDialog(null, "Do You Want To Close From?","Resgister From",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
//            System.exit(0);
//        }
          login.main(null);
          this.dispose();
    }//GEN-LAST:event_btnconcleActionPerformed

    private void btnresgisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresgisterActionPerformed
        // TODO add your handling code here:
        String Username = txtusername.getText();
        String pass = String.valueOf(txtpass.getPassword());
        String comfimpass = String.valueOf(txtcomfimpass.getPassword());
        
        if (pass.equals(comfimpass)) {

            try {
                Statement s = (Statement) connection.getDatacon().createStatement();
                s.execute("INSERT INTO `tbl_user`(`username`, `password`) VALUES ('" + Username + "','" + pass + "')");
            } catch (Exception e) {
                
            }
            JOptionPane.showConfirmDialog(this, "Your Account Resgister");
        } else {
            JOptionPane.showConfirmDialog(this, "pleas Check Your Password...!");
        }
        ClearData();
    }//GEN-LAST:event_btnresgisterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try {
              connection.Connectiondb("root", "", "student", "localhost");
//              JOptionPane.showMessageDialog(this, "Login SuccessFully...!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rigister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconcle;
    private javax.swing.JButton btnresgister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtcomfimpass;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
